### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar una pelicula
GET http://localhost:3000/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

### Recuperar peliculas por género
GET http://localhost:3000/movies?genre=fantasy

### Crear una nueva pelicula
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Age of Ultron",
    "year": 2015,
    "director": "Bryan Singer",
    "duration": 142,
    "poster": "https://m.media-amazon.com/images/M/MV5BODBhYTg1NGQtNGVmNS00ZTdiLThjYTYtZDFkNzRiNTZmNDZjXkEyXkFqcGc@._V1_.jpg",
    "genre": ["Action", "Adventure", "Sci-Fi"],
    "rate": 9.3
}

### Eliminar una pelicula
DELETE http://localhost:3000/movies/5ad1a235-0d9c-410a-b32b-220d91689a08   

### Actualizar una pelicula
PATCH  http://localhost:3000/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
Content-Type: application/json

{
    "year": 1978
}